### ISSUE TITLE
训练和测试

### ISSUE THREAD

**Issue by 1998wq** [Chnja/RDPNet#7]
作者你好，没有训练和测试文件吗

**Comment by Chnja** [comment]
训练和测试的文件都比较容易编写，大家也都会有所差别，我们目前没有开源的计划😂

**Comment by 1998wq** [comment]
作者你好，因为我想学学你这个代码还有论文，所以确实需要你们的训练和测试文件，能不能给我私发一下，谢谢！！
***@***.***



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月17日(周六) 晚上6:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Chnja/RDPNet] 训练和测试 (Issue #7)




 
训练和测试的文件都比较容易编写，大家也都会有所差别，我们目前没有开源的计划😂

**Comment by WesternTrail** [comment]
你这是开的啥源，训练验证评估脚本都没有，太六了。

**Comment by WesternTrail** [comment]
不开源就别往上贴代码，别人复现还得费劲，你忽悠忽悠审稿人也就算了。怕被别人知道你用测试集训练了？
