### ISSUE TITLE
出现了TypeError: only integer tensors of a single element can be converted to an index问题

### ISSUE THREAD

**Issue by youmuzi** [Chnja/RDPNet#9]
您好，我在使用这个loss的时候，发现出现了这样的问题
TypeError: only integer tensors of a single element can be converted to an index
出现的位置在这里，您能帮忙看下吗
![image](https://github.com/Chnja/RDPNet/assets/30626601/2b573ac8-d899-441a-8d69-094e32c41690)

**Comment by Chnja** [comment]
第13行应该为
```python
ksize = self.KSIZE
```
不好意思应该是复制代码的时候打错了😒
